#!/usr/bin/env python3

def main():    
    usr_name = input("Please enter your name:\n>") 
              

    usr_name = usr_name.title()    
    usr_date = int(input("Please enter your birth year in YYYY format, e.g 2010:\n>"))
            
    usr_date_difference = usr_date - 1960
    usr_modulo = usr_date_difference % 12

    zodiac_dict = {0:"Rat, you are artistic, sociable, industrious, charming, and intelligent", 
            1:"Ox, you are strong, thorough, determined, loyal, and reliable.", 2:"Tiger, you are courageous, enthusiastic, confident, charismatic, and a leader.", 3:"Rabbit, you are vigilant, witty, quick-minded, and ingenious.", 4:"Dragon, you are talented, powerful, lucky, and successfull.", 5:"Snake, you are wise, like to work alone, and determined.", 6:"Horse, you are animated, active, and energetic.", 7:"Sheep, you are creative, resilient, gentle, mild-mannered, and shy.", 8:"Monkey, you are sharp, smart, curious, and mischievious.", 9:"Rooster, you are hardworking, resourceful, courageous, and talented.", 10:"Dog, you are loyal, honest, cautious, and kind.", 11:"Pig, you are a symbol of wealth, honesty, and practicality." }


    print(f"{usr_name} your zodiac sign is {zodiac_dict[usr_modulo]}")


main()
